# Generated by Django 4.1.5 on 2023-03-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userincome", "0002_alter_userincome_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("writer", models.CharField(max_length=255)),
                ("publishedat", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Consulting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("exp", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("scheduledat", models.CharField(max_length=255)),
                ("booked", models.BooleanField(default=False)),
            ],
        ),
    ]
