# Generated by Django 4.1.5 on 2023-03-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userincome", "0004_consulting_razor_pay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulting",
            name="meduration",
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name="consulting",
            name="zoomlink",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
