# Generated by Django 4.1.5 on 2023-03-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userincome", "0005_consulting_meduration_consulting_zoomlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulting",
            name="meetingid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
