# Generated by Django 4.1.5 on 2023-03-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userincome", "0007_alter_consulting_scheduledat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulting",
            name="scheduledat",
            field=models.CharField(default="2023-03-26 18:00", max_length=255),
        ),
    ]
