# Generated by Django 4.1.5 on 2023-04-17 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userincome", "0008_alter_consulting_scheduledat"),
    ]

    operations = [
        migrations.RemoveField(model_name="consulting", name="booked",),
        migrations.RemoveField(model_name="consulting", name="razor_pay_order_id",),
        migrations.RemoveField(model_name="consulting", name="razor_pay_payment_id",),
        migrations.RemoveField(
            model_name="consulting", name="razor_pay_payment_signature",
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee", models.CharField(max_length=255)),
                (
                    "razor_pay_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razor_pay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razor_pay_payment_signature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consulting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userincome.consulting",
                    ),
                ),
            ],
        ),
    ]
